### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by petervolvowinz** [COVESA/vissr#37]
The current registered timestamp tied to a data point is when the viss server receives the signal from the southbound connection.
When we are using recorded data and actually need to refer to the actual time when the signal was conceived we cannot use the vissr server. That limits uses. Therefore it should be possible to use the timestamp coming from the vehicle interface such as CAN/FLEXRAY etc...

**Comment by UlfBj** [comment]
Is it not the case that it is the responsibility of the feeder to geenrate a timestamp when it writes a data point into the statestorage?
If it is, then the suggestion above becomes a feeder implementation issue. Feeders that receive a timestamp together with the data value via the vehicle interface should then use that instead of reading the system clock.
If it is not the case, then we should change the behavior to the above.

**Comment by petervolvowinz** [comment]
Yes, the issue was however that the utility limited the actual set timestamp.
Anyway, I have fixed that.


From: Ulf Björkengren ***@***.***>
Date: Tuesday, June 18, 2024 at 2:13 PM
To: COVESA/vissr ***@***.***>
Cc: Winzell, Peter ***@***.***>, Author ***@***.***>
Subject: Re: [COVESA/vissr] Time (Issue #37)

Is it not the case that it is the responsibility of the feeder to geenrate a timestamp when it writes a data point into the statestorage?
If it is, then the suggestion above becomes a feeder implementation issue. Feeders that receive a timestamp together with the data value via the vehicle interface should then use that instead of reading the system clock.
If it is not the case, then we should change the behavior to the above.

**Comment by petervolvowinz** [comment]
I think we can close this one.
